# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'ZXScollPageViewDemo' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod ‘MBProgressHUD’

  target 'ZXScollPageViewDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZXScollPageViewDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
